<?php

namespace Database\Seeders;

use App\Models\Brand;
use Illuminate\Database\Seeder;

class CarBrandsSeeder extends Seeder
{

    public function run()
    {
        $carBrands = [
            ['name' => 'Toyota', 'name_e' => 'Toyota'],
            ['name' => 'Honda', 'name_e' => 'Honda'],
            ['name' => 'Ford', 'name_e' => 'Ford'],
            ['name' => 'Chevrolet', 'name_e' => 'Chevrolet'],
            ['name' => 'Volkswagen', 'name_e' => 'Volkswagen'],
            ['name' => 'Nissan', 'name_e' => 'Nissan'],
            ['name' => 'BMW', 'name_e' => 'BMW'],
            ['name' => 'Mercedes-Benz', 'name_e' => 'Mercedes-Benz'],
            ['name' => 'Audi', 'name_e' => 'Audi'],
            ['name' => 'Hyundai', 'name_e' => 'Hyundai'],
            ['name' => 'Kia', 'name_e' => 'Kia'],
            ['name' => 'Tesla', 'name_e' => 'Tesla'],
            ['name' => 'Subaru', 'name_e' => 'Subaru'],
            ['name' => 'Mazda', 'name_e' => 'Mazda'],
            ['name' => 'Lexus', 'name_e' => 'Lexus'],
            ['name' => 'Volvo', 'name_e' => 'Volvo'],
            ['name' => 'Porsche', 'name_e' => 'Porsche'],
            ['name' => 'Land Rover', 'name_e' => 'Land Rover'],
            ['name' => 'Fiat', 'name_e' => 'Fiat'],
            ['name' => 'Mitsubishi', 'name_e' => 'Mitsubishi'],
            ['name' => 'Jeep', 'name_e' => 'Jeep'],
            ['name' => 'Buick', 'name_e' => 'Buick'],
            ['name' => 'Cadillac', 'name_e' => 'Cadillac'],
            ['name' => 'Chrysler', 'name_e' => 'Chrysler'],
            ['name' => 'Dodge', 'name_e' => 'Dodge'],
            ['name' => 'Jaguar', 'name_e' => 'Jaguar'],
            ['name' => 'Ram', 'name_e' => 'Ram'],
            ['name' => 'Genesis', 'name_e' => 'Genesis'],
            ['name' => 'Alfa', 'name_e' => 'Alfa'],
            ['name' => 'Mini', 'name_e' => 'Mini'],
            ['name' => 'Maserati', 'name_e' => 'Maserati'],
            ['name' => 'Acura', 'name_e' => 'Acura'],
            ['name' => 'Infiniti', 'name_e' => 'Infiniti'],
            ['name' => 'Citroën', 'name_e' => 'Citroën'],
            ['name' => 'Peugeot', 'name_e' => 'Peugeot'],
            ['name' => 'Renault', 'name_e' => 'Renault'],
            ['name' => 'Skoda', 'name_e' => 'Skoda'],
            ['name' => 'Seat', 'name_e' => 'Seat'],
            ['name' => 'Ferrari', 'name_e' => 'Ferrari'],
            ['name' => 'Lamborghini', 'name_e' => 'Lamborghini'],
            ['name' => 'McLaren', 'name_e' => 'McLaren'],
            ['name' => 'Bugatti', 'name_e' => 'Bugatti'],
            ['name' => 'Lotus', 'name_e' => 'Lotus'],
            ['name' => 'Smart', 'name_e' => 'Smart'],
            ['name' => 'Alpine', 'name_e' => 'Alpine'],
            ['name' => 'Dacia', 'name_e' => 'Dacia'],
            ['name' => 'Suzuki', 'name_e' => 'Suzuki'],
            ['name' => 'Mahindra', 'name_e' => 'Mahindra'],
            ['name' => 'Tata Motors', 'name_e' => 'Tata Motors'],
            ['name' => 'Geely', 'name_e' => 'Geely'],
            ['name' => 'Chery', 'name_e' => 'Chery'],
            ['name' => 'BYD', 'name_e' => 'BYD'],
            ['name' => 'Great Wall Motors', 'name_e' => 'Great Wall Motors'],
            ['name' => 'Proton', 'name_e' => 'Proton'],
            ['name' => 'Perodua', 'name_e' => 'Perodua'],
            ['name' => 'Changan', 'name_e' => 'Changan'],
            ['name' => 'SsangYong', 'name_e' => 'SsangYong'],
            ['name' => 'Brilliance', 'name_e' => 'Brilliance'],
            ['name' => 'Dongfeng', 'name_e' => 'Dongfeng'],
            ['name' => 'Isuzu', 'name_e' => 'Isuzu'],
            ['name' => 'Foton', 'name_e' => 'Foton'],
            ['name' => 'JAC Motors', 'name_e' => 'JAC Motors'],
            ['name' => 'GAC Motor', 'name_e' => 'GAC Motor'],
            ['name' => 'Haima', 'name_e' => 'Haima'],
            ['name' => 'MG (Morris Garages', 'name_e' => 'MG (Morris Garages'],
            ['name' => 'Lada', 'name_e' => 'Lada'],
            ['name' => 'Tatra', 'name_e' => 'Tatra'],
            ['name' => 'Zotye', 'name_e' => 'Zotye'],
            ['name' => 'Wuling', 'name_e' => 'Wuling'],
            ['name' => 'Lifan', 'name_e' => 'Lifan'],
            ['name' => 'Haval', 'name_e' => 'Haval'],
            ['name' => 'BAIC (Beijing Automotive)', 'name_e' => 'BAIC (Beijing Automotive)'],
            ['name' => 'FAW (First Automobile Works)', 'name_e' => 'FAW (First Automobile Works)'],
            ['name' => 'Iveco', 'name_e' => 'Iveco'],
            ['name' => 'MAN', 'name_e' => 'MAN'],
            ['name' => 'Scania', 'name_e' => 'Scania'],
            ['name' => 'Dacia (Renault Group)', 'name_e' => 'Dacia (Renault Group)'],
            ['name' => 'Mahindra Electric', 'name_e' => 'Mahindra Electric'],
            ['name' => 'NIO', 'name_e' => 'NIO'],
            ['name' => 'Lucid Motors', 'name_e' => 'Lucid Motors'],
            ['name' => 'Rivian', 'name_e' => 'Rivian'],
            ['name' => 'Polestar', 'name_e' => 'Polestar'],
            ['name' => 'Rimac', 'name_e' => 'Rimac'],
            ['name' => 'Bollinger', 'name_e' => 'Bollinger'],
            ['name' => 'Rivian', 'name_e' => 'Rivian'],
            ['name' => 'Polestar', 'name_e' => 'Polestar'],
            ['name' => 'Faraday Future', 'name_e' => 'Faraday Future'],
            ['name' => 'Bollinger Motors', 'name_e' => 'Bollinger Motors'],
            ['name' => 'Karma Automotive', 'name_e' => 'Karma Automotive'],
            ['name' => 'Rimac Automobili', 'name_e' => 'Rimac Automobili'],
            ['name' => 'Lucid Motors', 'name_e' => 'Lucid Motors'],
            ['name' => 'BYTON', 'name_e' => 'BYTON'],
            ['name' => 'Arcfox', 'name_e' => 'Arcfox'],
            ['name' => 'BAC (Briggs Automotive Company)', 'name_e' => 'BAC (Briggs Automotive Company)'],
            ['name' => 'Koenigsegg', 'name_e' => 'Koenigsegg'],
            ['name' => 'TVR', 'name_e' => 'TVR'],
            ['name' => 'Spyker', 'name_e' => 'Spyker'],
            ['name' => 'Pagani', 'name_e' => 'Pagani'],
            ['name' => 'Donkervoort', 'name_e' => 'Donkervoort'],
            ['name' => 'Apollo', 'name_e' => 'Apollo'],
            ['name' => 'Zenvo', 'name_e' => 'Zenvo'],
            ['name' => 'Wiesmann', 'name_e' => 'Wiesmann'],
            ['name' => 'Arrinera', 'name_e' => 'Arrinera'],
            ['name' => 'Caterham', 'name_e' => 'Caterham'],
            ['name' => 'Ginetta', 'name_e' => 'Ginetta'],
            ['name' => 'Panoz', 'name_e' => 'Panoz'],
            ['name' => 'VUHL', 'name_e' => 'VUHL'],
            ['name' => 'Saker', 'name_e' => 'Saker'],
            ['name' => 'Falcon Motorsports', 'name_e' => 'Falcon Motorsports'],
            ['name' => 'Noble', 'name_e' => 'Noble'],
            ['name' => 'Savage Rivale', 'name_e' => 'Savage Rivale'],
            ['name' => 'Sin Cars', 'name_e' => 'Sin Cars'],
            ['name' => 'Bristol Cars', 'name_e' => 'Bristol Cars'],
            ['name' => 'GTA Motor', 'name_e' => 'GTA Motor'],
            ['name' => 'Fornasari', 'name_e' => 'Fornasari'],
            ['name' => 'Melkus', 'name_e' => 'Melkus'],
            ['name' => 'Zarooq Motors', 'name_e' => 'Zarooq Motors'],
            ['name' => 'Quantum', 'name_e' => 'Quantum'],
            ['name' => 'Ligier', 'name_e' => 'Ligier'],
            ['name' => 'Ariel Motor Company', 'name_e' => 'Ariel Motor Company'],

            ['name' => 'Morgan Motor Company', 'name_e' => 'Morgan Motor Company'],
            ['name' => 'Czinger Vehicles', 'name_e' => 'Czinger Vehicles'],
            ['name' => 'Donkervoort', 'name_e' => 'Donkervoort'],
            ['name' => 'KTM', 'name_e' => 'KTM'],
            ['name' => 'Wuling Motors', 'name_e' => 'Wuling Motors'],
            ['name' => 'Sbarro', 'name_e' => 'Sbarro'],

        ];

        foreach ($carBrands as $brand) {
            Brand::create([
                'name' => $brand['name'],
                'name_e' => $brand['name_e'],
            ]);
        }

    }

}
